config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :movies
  resources :series
  resources :tv_shows
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update]

  def index
  	@movies = Movie.all
  end

  def new
  	@movie = Movie.new
  end

  def edit
  end

  def show
  	@movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :path)
    end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
	before_action :set_tv_show, only: [:show, :edit, :update]

  def index
  	@tv_shows = TvShow.all
  end

  def new
  	@tv_show = TvShow.new
  end

  def edit
  end

  def show
  	@tv_show = TvShow.find(params[:id])
  end

  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'tv_show was successfully created.' }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1
  # PATCH/PUT /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to @tv_show, notice: 'tv_show was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_show_params
      params.require(:tv_show).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCineStream</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.input :title %>
  <%= f.input :path %>
  <%= f.button :submit %>
<% end %>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<% @movies.each do |movie| %>
  <p><%= link_to movie.title, movie_path(movie) %></p>
<%end %>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<%= render 'form' %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<iframe src="<%= @movie.path %>"></iframe>

<%= link_to 'Retour', movies_path(@movies) %>

app/views/tv_shows/_form.html.erb
<%= simple_form_for @tv_show do |f| %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Edit Tv Show</h1>
<%= render 'form' %>

app/views/tv_shows/index.html.erb
<h1>Tv Show#index</h1>
<% @tv_shows.each do |tv_show| %>
  <p><%= link_to tv_show.title, tv_show_path(tv_show) %></p>
<%end %>

app/views/tv_shows/new.html.erb
<h1>New tv show</h1>
<%= render 'form' %>

app/views/tv_shows/show.html.erb
<h1><%= @tv_show.title %></h1>

<%= link_to 'Retour', tv_shows_path(@tv_shows) %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to 'Movies', movies_path(@movies) %>
<%= link_to 'Series', series_index_path(@series) %>
<%= link_to 'Series', tv_shows_path(@tv_shows) %>